# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  BuildTask: 'BuildAndCreatePackages'
  BuildConfiguration: 'RELEASE'



stages:
- stage: Build
  displayName: 'Build Studio Community Toolkit'
  jobs:
  - job: Do_Build
    displayName: 'Do build'
    pool:
      name: Studio-OX
      demands:
      - msbuild
      - Agent.ComputerName -equals CLJVMOX2017A2
      - visualstudio
    steps:
    - task: NuGetToolInstaller@0
    - task: CmdLine@2
      inputs:
        script: |
          .\build.cmd @BuildTask @BuildConfiguration
      
          displayName: 'Start building the BuildToolkit'
stage: provision_to_production_env
  displayName: 'Provision resources to production environment'
  jobs:
  - job: production_provisioning
    displayName: 'Prodduction env provisioning job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo provisioning to production environment
      displayName: 'production environment provisioning'
    
    

