# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Studio-OX
  demands:
  - msbuild
  - Agent.ComputerName -equals CLJVMOX2017A2
  - visualstudio

steps:
- task: NuGetToolInstaller@0
- task: CmdLine@2
  inputs:
    script: |
      .\build.cmd CreatePackages RELEASE
      
      displayName: 'Start building the BuildToolkit'
